import './globals.css'
import Header from '@/components/layout/Header'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='dark' h-full>
      <body dark="text-white bg-slate-700" h-full flex flex-col>
        <Header/>
        <main p="2 md:4" grow>
          {children}
        </main>
      </body>
    </html>
  )
}
